### PR TITLE
Switch to numpy.ndarray.tobytes for binarizing adm_batch.

### PR DESCRIPTION
**Pull request by carterturn**
This PR implements the more efficient binarization method suggested by dihm in https://github.com/labscript-suite/PrawnBlaster/pull/25.

For the maximum number of instructions, this reduces binarization time from ~100ms to ~20ms, in total reducing programming time by ~20%.

### CODE REVIEW

**Comment by dihm** [comment]
@carterturn Thanks for bringing this change over.

I was thinking about this over the long weekend and had a thought. What if we updated the labscript_device to produce the correct array on compilation, instead of having to create it here on the fly? That would mimic what most labscript-devices do (including the prawnblaster) which I think would be a plus. It would also necessitate reworking a few things, but probably not in a terribly difficult way. Thoughts?

**Comment by dihm** [comment]
In light of the fact that #4 has not been merged yet, I say let's go ahead and merge this as-is. If we want to implement the change, we can do it in another PR after the merge conflicts are resolved.

**Comment by carterturn** [comment]
@dihm The array you are considering producing during compilation would be the combination of `do_data` and `reps_data`, right? I think storing those together does make sense (I believe it is just a result of the evolution of the device that this is not the case). The one thing to be careful of for that is that the different datatypes for the two columns (uint16 for the do_data and uint32 for the reps_data) are preserved across the HDF5 conversion, but this is probably possible.
It would probably be good to implement that on top of #4 though.

**Comment by dihm** [comment]
That is precisely the array I'm thinking to store. And I know the h5 file preserves mixed types from structured array (it's a fairly common pattern in other devices). I think you can go ahead and click merge here and I'll worry about getting #4 merged later this weekend.

**Pull request merged**
